### ISSUE TITLE
Central search component - results viewing services

### ISSUE THREAD

**Issue by Andreasr28** [GDI-HE/GeoPortal.rlp#24]
When using the central search, there are not only filter by expression, there are two dynamic settings for making the result more usable. 
- Results per page > default "10"
- Sort by > default "demand"

Just in case the search is not precise enough through the use of filters, the resultnummber might be so big that only single layers might be shown, due the default settings of sort an results per page, regardless of the wms where the layers are includet.
This can cause confusion.
 
Proposal - change default settings of sort an results:
- Maybe a higher number of results per page and
- maybe sort by identification number, 
will prevent this cause.

**Comment by karlbrink** [comment]
@Andreasr28

**perhaps we should try to change the user expectation - now it's called:**
- "Web Map **Services**" | "Darstellungsdienste" 

**but in fact the results are showing :**
- "Web Map **Layers**" | "Kartenebenen"


**because of the number of hits:**
- we can try a higher number of hits as default for a fixed period of time, then we could evaluate if there are some performance issues - default: 30 ??
- changing the default "sort by" to identification number doesn't make sense to me. the layer numbers does not represent the hierarchy of a WebMapService - it could represent it for a period of time, but after performing an update of the Service this will definitly change.
- **you can see all layers belonging together under the dataset results being represented by all viewing layers and even download options**

**approaches i can see is:**
1. we could hide the Layer results if performing a standard search. it would be still available with the explicit filter. <- i like this most.
2. we could change the order of the result categories: we can bring the focus on dataset results due to moving it to the top of the results <- mmmmh yaahhh ooookay
3. publishing organisations should write the best possible metadata for every layer that matters for them in a search result. <- i don't believe this will ever happen

**Comment by Andreasr28** [comment]
Good first draw in https://prototyp.geoportal.hessen.de/ ! 

- renaming Darstellungsdienste into Kartenebenen (landing page, central search hits, filter)
-  hide Layer results for Kartenebenen
- change the order

The conversions in both places "landingpage" and "central search" looks good.
![Kartenebenen](https://user-images.githubusercontent.com/75111073/177292678-6a186034-7223-49e8-95ea-e72f11c96ed5.PNG)
![Filter](https://user-images.githubusercontent.com/75111073/177292340-55c4742a-844f-4a91-93d3-1576ac42c435.PNG)

The implementation in the productive system is still ongoing ?
landingpage  > ready 
![Kartenebenen_2](https://user-images.githubusercontent.com/75111073/177292806-ad4a9bf0-012b-4c44-b0b6-6d0bc253215f.PNG)

central search and filter still to come?
